resolver: lts-16.10

packages:
  - .

extra-deps:
  - data-interval-2.0.1
  - plots-0.1.1.2

flags:
  diagrams:
    svg: true
    ps: false
    rasterific: false
    canvas: false
    gtk: false
    cairo: false

ghc-options:
  "$locals": -fno-warn-unused-do-bind
