---
name:                csv-to-score
version:             0.1.0.0
github:              "bjartur/Master/tree/master/csv-to-score"
author:              "Bjartur Thorlacius"
maintainer:          "bjt9@hi.is"
copyright:           "Copyright (c) 2018–2020 Bjartur Thorlacius"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis:            Find respiratory effort crescendo events.
category:            Science

description:         See README.md

dependencies:
  - base >= 4.7 && < 5



library:
  source-dirs: src
  dependencies:
  - listsafe

executables:
  csv-to-score:
    main:                Main.hs
    source-dirs:         cmd
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - csv-to-score
      - filepath < 1.5

tests:
  csv-to-score-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - csv-to-score
      - QuickCheck
      - hspec
