---
name: plot
version: 0.1.0.0
github: "bjartur/Master/tree/master/plot"
author: "Bjartur Thorlacius"
maintainer: "bjt9@hi.is"
copyright: "Copyright (c) 2018–2020 Bjartur Thorlacius"

dependencies:
  - plots >= 0.1.1.2
  - base >= 4.12.0.0 && < 4.14
  - diagrams-svg < 1.5
  - diagrams-lib < 1.5
  - diagrams-core >= 1.4.2 && < 1.5
  - semigroups < 0.20
  - linear >= 1.20.9 && < 1.21
  - directory >= 1.2.5.0 && < 1.4
  - filepath < 1.5
  - lens >= 4.6 && < 5.0
  - colour >= 1.0.0 && < 2.4
  - statistics <= 0.16 && >= 0.15.2.0
  - vector >= 0.12.0.3 && <= 0.13
  - deepseq
  - bjartur-lib

executables:
  plot:
    main: Main.hs
    source-dirs: .
