---
name:                nox2score
version:             0.1.0.0
github:              "bjartur/Master/nox2score"
author:              "Bjartur Thorlacius"
maintainer:          "bjt9@hi.is"
copyright:           "Copyright (c) 2018–2021 Bjartur Thorlacius"

dependencies:
  - base < 4.14 && >= 2.10
  - filepath < 1.5 && >= 1.4
  - directory < 1.4 && >= 1.3.4.0

executables:
  nox2score:
    main: Main.hs

tests:
  spec:
    main: Tests.hs
    other-modules: Main
    dependencies:
    - hspec
    - QuickCheck
    ghc-options: -main-is Tests
