.ONESHELL:
demo: nadir/BbB/20141218T214507\ \-\ eb35b.txt
nadir/BbB/20141218T214507\ \-\ eb35b.txt: BbB_nadir.py extract.py extract_nadirs.py
	source activate master
	python BbB_nadir.py
.PHONY: demo
